# Dependencies
markdown:         redcarpet
gems:
- jemoji
- jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Hearthstone
tagline:          ''
description:      ''
url:              http://hearthstone.oblio360.com

author:
  name:           'Constantin Caraivan'
  url:            https://twitter.com/oblio360

paginate:         5
